name: Update NPM Package

on:
  # Run weekly on Sunday at 00:00 UTC
  schedule:
    - cron: '0 0 * * 0'
  
  # Allow manual triggering
  workflow_dispatch:

  # Run when Python scripts are updated
  push:
    paths:
      - 'main.py'
      - 'merge_api.py'
      - '.github/workflows/update-npm-package.yml'

# Add permissions for the GITHUB_TOKEN
permissions:
  contents: write

jobs:
  update-package:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
      
      - name: Download and sort npm package
        run: |
          # Make scripts executable
          chmod +x main.py
          # Run the main script to download and sort files
          python main.py
      
      - name: Generate merged API file
        run: |
          # Make script executable
          chmod +x merge_api.py
          # Run the merge script to generate the merged API file
          python merge_api.py
      
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
      - name: Commit changes
        run: |
          # Get the current package version from README
          VERSION=$(grep -oP "Package Version:\s*\K[^_].*" README.md || echo "Unknown")
          
          git add api/ implementation/ not_needed/ api_merged.md README.md
          
          # Only commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update package to version $VERSION"
            echo "Changes committed"
          fi
      
      - name: Push changes
        # Use git push directly instead of the third-party action
        run: git push